[programs.localnet]
cpi_marinade = "GjVoL49VRjsSXjdG3FAfkXgdwk7VfAPpV9K23gx8C6Na"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/chalda/.config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
