[features]
seeds = false
skip-lint = false
[programs.localnet]
cpi_marinade = "Em26cSRXE9fxSPNnkHUh8Wmvqh279Jo7StWuCDTCLLSe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/chalda/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
